name: forecast_v3

description: Forecast App built with Flutter and Redux.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_redux: ^0.10.0
  flutter_svg: ^1.1.6
  flutter_weather_bg_null_safety: ^1.0.0
  geolocator: ^9.0.2
  geolocator_windows: ^0.1.1
  get: ^4.6.5
  google_geocoding_api: ^1.2.0
  http: ^0.13.5
  pull_to_refresh: ^2.0.0
  redux: ^5.0.0
  redux_logging: ^0.5.0
  redux_thunk: ^0.4.0
  toggle_switch: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
