final Map<String, String> englishStrings = {
  'app_title': 'Forecast',
  'loading': 'Loading data, please wait...',
  'settings.settings_header': 'Settings',
  'settings.select_language': 'Select Language',
  'settings.en': 'English',
  'settings.fr': 'Français',
  'settings.es': 'Español',
  'settings.enable_backgrounds': 'Animated Backgrounds',
  'settings.enable_dark_mode': 'Dark Mode',
  'settings.temp_units': 'Temp Units',
  'settings.wind_speed_units': 'Wind Speed Units',
  'settings.air_pressure_units': 'Air Pressure Units',
  'settings.aqi_units': 'Air Quality Units',
  'settings.locations_header': 'Locations',
  'settings.find_location': 'Search ...',
  'settings.current_location': 'Current location',
  'settings.about_app': 'About',
  'settings.off': 'Off',
  'settings.on': 'On',
  'settings.us_aqi': 'US EPA Index',
  'settings.gb_aqi': 'GB Defra Index',
};
