const Map<String, String> frenchStrings = <String, String>{
  'app_title': 'Forecast',
  'loading': 'Loading data, please wait...',
  'OK': 'ok',
  'error': 'Erreur',
  'save-error':
      "Nous n'avons pu enregistrement vos paramètres, essayez plus tard",

  /// Conditions card
  'feelslike': 'Feels like @temp',

  /// Air quality strings
  'aqi-good': 'Good',
  'aqi-moderate': 'Moderate',
  'aqi-unhealthylite': 'Unhealthy for sensitive',
  'aqi-unhealthy': 'Unhealthy',
  'aqi-veryunhealthy': 'Very Unhealthy',
  'aqi-hazardous': 'Hazardous',
  'aqi-low': 'Low',
  'aqi-high': 'High',
  'aqi-veryhigh': 'Very High',

  /// Settings strings
  'settings_header': 'Settings',
  'select_language': 'Select Language',
  'en': 'English',
  'fr': 'Français',
  'es': 'Español',
  'enable_backgrounds': 'Animated Backgrounds',
  'enable_dark_mode': 'Dark Mode',
  'temp_units': 'Temp Units',
  'wind_speed_units': 'Wind Speed Units',
  'air_pressure_units': 'Air Pressure Units',
  'aqi_units': 'Air Quality Units',
  'locations_header': 'Locations',
  'find_location': 'Search ...',
  'current_location': 'Current location',
  'about_app': 'About',
  'off': 'Off',
  'on': 'On',
  'us_aqi': 'US EPA Index',
  'gb_aqi': 'GB Defra Index',

  /// Weather conditions
  'Sunny': 'Sunny',
  'Clear': 'Clear',
  'Partly cloudy': 'Partly cloudy',
  'Cloudy': 'Cloudy',
  'Overcast': 'Overcast',
  'Mist': 'Mist',
  'Patchy rain possible': 'Patchy rain possible',
  'Patchy snow possible': 'Patchy snow possible',
  'Patchy sleet possible': 'Patchy sleet possible',
  'Patchy freezing drizzle possible': 'Patchy freezing drizzle possible',
  'Thundery outbreaks possible': 'Thundery outbreaks possible',
  'Blowing snow': 'Blowing snow',
  'Blizzard': 'Blizzard',
  'Fog': 'Fog',
  'Freezing fog': 'Freezing fog',
  'Patchy light drizzle': 'Patchy light drizzle',
  'Light drizzle': 'Light drizzle',
  'Freezing drizzle': 'Freezing drizzle',
  'Heavy freezing drizzle': 'Heavy freezing drizzle',
  'Patchy light rain': 'Patchy light rain',
  'Light rain': 'Light rain',
  'Moderate rain at times': 'Moderate rain at times',
  'Moderate rain': 'Moderate rain',
  'Heavy rain at times': 'Heavy rain at times',
  'Heavy rain': 'Heavy rain',
  'Light freezing rain': 'Light freezing rain',
  'Moderate or heavy freezing rain': 'Moderate or heavy freezing rain',
  'Light sleet': 'Light sleet',
  'Moderate or heavy sleet': 'Moderate or heavy sleet',
  'Patchy light snow': 'Patchy light snow',
  'Light snow': 'Light snow',
  'Patchy moderate snow': 'Patchy moderate snow',
  'Moderate snow': 'Moderate snow',
  'Patchy heavy snow': 'Patchy heavy snow',
  'Heavy snow': 'Heavy snow',
  'Ice pellets': 'Ice pellets',
  'Light rain shower': 'Light rain shower',
  'Moderate or heavy rain shower': 'Moderate or heavy rain shower',
  'Torrential rain shower': 'Torrential rain shower',
  'Light sleet showers': 'Light sleet showers',
  'Moderate or heavy sleet showers': 'Moderate or heavy sleet showers',
  'Light snow showers': 'Light snow showers',
  'Moderate or heavy snow showers': 'Moderate or heavy snow showers',
  'Light showers of ice pellets': 'Light showers of ice pellets',
  'Moderate or heavy showers of ice pellets':
      'Moderate or heavy showers of ice pellets',
  'Patchy light rain with thunder': 'Patchy light rain with thunder',
  'Moderate or heavy rain with thunder': 'Moderate or heavy rain with thunder',
  'Patchy light snow with thunder': 'Patchy light snow with thunder',
  'Moderate or heavy snow with thunder': 'Moderate or heavy snow with thunder',

  /// Astro data card
  'sunrise': 'Sunrise',
  'sunset': 'Sunset',
  'moonphase': 'Moon Phase',
  'New Moon': 'New Moon',
  'Waxing Crescent': 'Waxing Crescent',
  'First Quarter': 'First Quarter',
  'Waxing Gibbous': 'Waxing Gibbous',
  'Full Moon': 'Full Moon',
  'Waning Gibbous': 'Waning Gibbous',
  'Last Quarter': 'Last Quarter',
  'Waning Crescent': 'Waning Crescent',

  /// Environment card headers
  'humidity': 'Humidity',
  'uvindex': 'UV Index',
  'airquality': 'Air Quality',
  'wind': 'Wind',
  'airpressure': 'Air Pressure',

  /// Wind Compass directions
  'n': 'N',
  'nne': 'NNE',
  'ne': 'NE',
  'ene': 'ENE',
  'e': 'E',
  'ese': 'ESE',
  'se': 'SE',
  'sse': 'SSE',
  's': 'S',
  'ssw': 'SSW',
  'sw': 'SW',
  'wsw': 'WSW',
  'w': 'W',
  'wnw': 'WNW',
  'nw': 'NW',
  'nnw': 'NNW',

  // Weather alert dialog strings
  'alert': 'Alert',
  'severity': 'Severity',
  'areas-affected': 'Areas affected',
  'certainty': 'Certainty',
  'urgency': 'Urgency',
  'effective': 'Effective',
  'expires': 'Expires',
  'description': 'Description',
  'instructions': 'Instructions',
};
